package mybatis.model;

public class CardPrinting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARD_PRINTING.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARD_PRINTING.SETNUMBER
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private Integer setnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARD_PRINTING.CARD_ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private Integer cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARD_PRINTING.PRINTEDCARDSET_ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private Integer printedcardsetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARD_PRINTING.ID
     *
     * @return the value of PUBLIC.CARD_PRINTING.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARD_PRINTING.ID
     *
     * @param id the value for PUBLIC.CARD_PRINTING.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARD_PRINTING.SETNUMBER
     *
     * @return the value of PUBLIC.CARD_PRINTING.SETNUMBER
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public Integer getSetnumber() {
        return setnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARD_PRINTING.SETNUMBER
     *
     * @param setnumber the value for PUBLIC.CARD_PRINTING.SETNUMBER
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setSetnumber(Integer setnumber) {
        this.setnumber = setnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARD_PRINTING.CARD_ID
     *
     * @return the value of PUBLIC.CARD_PRINTING.CARD_ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARD_PRINTING.CARD_ID
     *
     * @param cardId the value for PUBLIC.CARD_PRINTING.CARD_ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARD_PRINTING.PRINTEDCARDSET_ID
     *
     * @return the value of PUBLIC.CARD_PRINTING.PRINTEDCARDSET_ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public Integer getPrintedcardsetId() {
        return printedcardsetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARD_PRINTING.PRINTEDCARDSET_ID
     *
     * @param printedcardsetId the value for PUBLIC.CARD_PRINTING.PRINTEDCARDSET_ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setPrintedcardsetId(Integer printedcardsetId) {
        this.printedcardsetId = printedcardsetId;
    }
}