package mybatis.model;

public class Card {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARD.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARD.NAME
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARD.ID
     *
     * @return the value of PUBLIC.CARD.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARD.ID
     *
     * @param id the value for PUBLIC.CARD.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARD.NAME
     *
     * @return the value of PUBLIC.CARD.NAME
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARD.NAME
     *
     * @param name the value for PUBLIC.CARD.NAME
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}