package mybatis.model;

public class Set {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SET.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SET.CODE
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SET.NAME
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SET.ID
     *
     * @return the value of PUBLIC.SET.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SET.ID
     *
     * @param id the value for PUBLIC.SET.ID
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SET.CODE
     *
     * @return the value of PUBLIC.SET.CODE
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SET.CODE
     *
     * @param code the value for PUBLIC.SET.CODE
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SET.NAME
     *
     * @return the value of PUBLIC.SET.NAME
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SET.NAME
     *
     * @param name the value for PUBLIC.SET.NAME
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}