package mybatis.dao;

import java.util.List;
import persistence.mybatis.model.Card;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    Card selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    List<Card> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    int updateByPrimaryKey(Card record);
}