package mybatis.dao;

import java.util.List;
import mybatis.model.CardPrinting;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CardPrintingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD_PRINTING
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD_PRINTING
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    int insert(CardPrinting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD_PRINTING
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    CardPrinting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD_PRINTING
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    List<CardPrinting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARD_PRINTING
     *
     * @mbg.generated Wed Apr 06 17:07:41 EEST 2022
     */
    int updateByPrimaryKey(CardPrinting record);
}